name: ESPHome CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - example.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Prepare secrets.yaml
        run: |
          echo "wifi_ssid: undefined" > secrets.yaml
          echo "wifi_password: undefined" >> secrets.yaml
          echo "captive_portal_ssid: undefined" >> secrets.yaml
          echo "captive_portal_password: undefined" >> secrets.yaml
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}
          version: ${{ matrix.esphome-version }}
